from datetime import datetime

MONTHS = ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']

OP_EXPENSES_TYPES = [
  "TELEFONÍA",
  "TRASLACIÓN",
  "DIFUSIÓN",
  "ACTIVIDADES DESTINADAS A LA INTERACCIÓN CON LA COMUNIDAD",
  "OFICINA",
  "CORRESPONDENCIA",
  "OFICINA",
  "WEB Y ALMACENAMIENTO",
  "OTROS",
]

OP_EXPENSES_OFFICE = [
  "ARRIENDO DE INMUEBLE",
  "EQUIPAMIENTO OFICINA PARLAMENTARIA",
  "MATERIALES DE OFICINA",
  "GASTOS DE MANTENCIÓN OFICINA PARLAMENTARIA (INMUEBLE)",
  "REPARACIONES LOCATIVAS DEL INMUEBLE",
  "ARRIENDO DE OFICINAS VIRTUALES",
  "ARRIENDO DE OFICINA MÓVIL",
  "MANTENCION Y REPARACIÓN DE OFICINA MÓVIL",
]

OP_EXPENSES_WEB = [
  "SERVICIOS WEB",
  "CONTRATACIÓN SERVICIO DE ALMACENAMIENTO",
]

OP_EXPENSES_OTHERS = [
  "TRASPASO DESDE GASTOS OPERACIONALES A ASIGNACIÓN PERSONAL DE APOYO",
  "CONSUMOS BÁSICOS",
  "HABILITACIÓN DE SEDES PARLAMENTARIAS (CON AUTORIZACIÓN DE CRAP)",
  "SEGUROS DE BIENES",
  "SERVICIOS MENORES",
  "COVID-19 PERSONAL DE APOYO",
]

def get_current_month():
  return datetime.now().month

def get_current_year():
  return datetime.now().year